version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_URI=mongodb://mongo:27017/devsecops
      - JWT_SECRET=SuperSecretJWTKey
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
